[package]
name = "url-resolver"
version = "0.1.0"
authors = ["vjy <reg@iavian.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.1"
reqwest = { version = "0.11", features = ["json","brotli","gzip"] }
tokio = { version = "1.14", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
# rsmc-tokio = "*"
# rsmc-core = "*"
# mobc = "0.7"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
panic = 'abort'