[package]
name = "url-resolver"
version = "0.1.0"
authors = ["vjy <reg@iavian.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.1"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.5", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
memcache = "*"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
panic = 'abort'