[package]
name = "url-resolver"
edition = "2021"
version = "0.1.4"
authors = ["vjy <reg@iavian.com>"]

[dependencies]
actix-web = "4.4.0"
bytes = "1.5.0"
reqwest = { version = "0.11", features = ["json", "brotli", "gzip", "rustls"] }
tokio = { version = "1.32.0", features = ["full"] }
serde = { version = "1.0.188", features = ["derive"] }
memcache-async = {version="0.6.4", optional = true }
futures = { version = "0.3.28", optional = true }
regex = "1.9.5"
url = "2.4.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
panic = 'abort'

[features]
default = ["memcache"]
memcache = ["memcache-async", "futures"]

