# fly.toml app configuration file generated for iavian-new-url-resolver on 2023-08-15T08:36:04+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "iavian-rust-url-resolver"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
